spring:
  profiles:
    active: dev
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  profiles: dev

server:
  port: 8081

mybatis:
  type-aliases-package: com.lu.ping.registration.entity
  mapper-locations: classpath:mapper/*.xml

